
GET http://localhost:4004/odata/v4/books/BooksSet

###
GET http://localhost:4004/odata/v4/books/BooksSet(9b1a29eb-8b7d-4b0a-9ecb-c7a6a31d37d9)


###
POST http://localhost:4004/odata/v4/books/BooksSet
Content-Type: application/json

{
   "Title": "The Great Gatsby1",
    "author": "F. Scott Fitzgerald1",
    "price": 499.99,
    "publishdate": "1985-03-15T10:00:00Z",
    "digitalCopy": false
}


###
PUT http://localhost:4004/odata/v4/books/BooksSet(0ede79e8-db4f-4752-be22-2f8a490b7373)
Content-Type: application/json

{
   "Title": "The Great Gatsby2",
    "author": "F. Scott Fitzgerald2",
    "price": 30.99,
    "publishdate": "1985-03-15T10:00:00Z",
    "digitalCopy": true
}

####
DELETE http://localhost:4004/odata/v4/books/BooksSet(414bd361-151f-45e9-a009-2f170f048c1c)