namespace db.booksdatamodelNamespace;

entity books {
    key ID          : UUID; // autogenerated unique identifier
        Title       : String;
        author      : String;
        price       : Decimal(10, 2);
        publishdate : DateTime; // date of publication
        digitalCopy : Boolean;
}

// db-booksdatamodel.books.csv : name of the CSV file to be imported into the books entity